### ISSUE TITLE
What did I do wrong?

### ISSUE THREAD

**Issue by jordanadania** [Wifsimster/adalight_ws2812#6]
When I upload the sketch, my LEDs turn green and stay green. I am using WS2812B so it's probably actually a BLUE in the code.

**Comment by Ekristoffe** [comment]
Are you using the same ino file ?
what pin is your LED on ?
Have you put a resistor and a capacitor ?
something like this:
![image](https://github.com/Wifsimster/adalight_ws2812/assets/5562219/3ab16a1a-01b7-4159-97ae-119a0b7222d8)

**Comment by jordanadania** [comment]
I lost interest in colored lights, sadly.
